const dummy = [
  {
    id: "P001",
    patient_name: "John Doe",
    last_scan_date: "2024-09-15",
    diagnosis: "Non-demented",
  },
  {
    id: "P002",
    patient_name: "Jane Smith",
    last_scan_date: "2024-08-25",
    diagnosis: "Mild dementia",
  },
  {
    id: "P003",
    patient_name: "Michael Johnson",
    last_scan_date: "2024-07-30",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P004",
    patient_name: "Emily Davis",
    last_scan_date: "2024-06-20",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P005",
    patient_name: "David Wilson",
    last_scan_date: "2024-09-05",
    diagnosis: "Non-demented",
  },
  {
    id: "P006",
    patient_name: "Sarah Brown",
    last_scan_date: "2024-08-10",
    diagnosis: "Mild dementia",
  },
  {
    id: "P007",
    patient_name: "Daniel Lee",
    last_scan_date: "2024-05-14",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P008",
    patient_name: "Laura Harris",
    last_scan_date: "2024-04-25",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P009",
    patient_name: "Kevin White",
    last_scan_date: "2024-10-02",
    diagnosis: "Non-demented",
  },
  {
    id: "P010",
    patient_name: "Olivia Martinez",
    last_scan_date: "2024-09-18",
    diagnosis: "Mild dementia",
  },
  {
    id: "P011",
    patient_name: "Liam Thomas",
    last_scan_date: "2024-07-22",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P012",
    patient_name: "Sophia Garcia",
    last_scan_date: "2024-06-05",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P013",
    patient_name: "James Anderson",
    last_scan_date: "2024-08-30",
    diagnosis: "Non-demented",
  },
  {
    id: "P014",
    patient_name: "Isabella Martinez",
    last_scan_date: "2024-05-10",
    diagnosis: "Mild dementia",
  },
  {
    id: "P015",
    patient_name: "Benjamin Clark",
    last_scan_date: "2024-03-18",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P016",
    patient_name: "Mason Allen",
    last_scan_date: "2024-04-03",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P017",
    patient_name: "Amelia Young",
    last_scan_date: "2024-09-12",
    diagnosis: "Non-demented",
  },
  {
    id: "P018",
    patient_name: "Alexander King",
    last_scan_date: "2024-10-10",
    diagnosis: "Mild dementia",
  },
  {
    id: "P019",
    patient_name: "Charlotte Scott",
    last_scan_date: "2024-07-05",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P020",
    patient_name: "Ethan Adams",
    last_scan_date: "2024-06-30",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P021",
    patient_name: "Avery Nelson",
    last_scan_date: "2024-05-22",
    diagnosis: "Non-demented",
  },
  {
    id: "P022",
    patient_name: "Ella Carter",
    last_scan_date: "2024-08-15",
    diagnosis: "Mild dementia",
  },
  {
    id: "P023",
    patient_name: "Jack Perez",
    last_scan_date: "2024-07-17",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P024",
    patient_name: "Harper Roberts",
    last_scan_date: "2024-06-12",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P025",
    patient_name: "Daniel Wilson",
    last_scan_date: "2024-09-23",
    diagnosis: "Non-demented",
  },
  {
    id: "P026",
    patient_name: "Grace Moore",
    last_scan_date: "2024-10-05",
    diagnosis: "Mild dementia",
  },
  {
    id: "P027",
    patient_name: "Matthew Taylor",
    last_scan_date: "2024-09-13",
    diagnosis: "Moderate dementia",
  },
  {
    id: "P028",
    patient_name: "Victoria Harris",
    last_scan_date: "2024-08-28",
    diagnosis: "Very mild dementia",
  },
  {
    id: "P029",
    patient_name: "Lucas Green",
    last_scan_date: "2024-07-27",
    diagnosis: "Non-demented",
  },
  {
    id: "P030",
    patient_name: "Chloe Walker",
    last_scan_date: "2024-06-18",
    diagnosis: "Mild dementia",
  },
];

export default dummy;
